int cpu_info();
int disk();
int distro();
int gpu_info();
int kernel();
int memory_info();
int package_count();
int refresh_rate();
int resolution();
int shell();
int terminal(char* const* envp);
int uptime_info();
int username_at_hostname();
int wm();
